### ISSUE TITLE
Text and equations are vertically offset.

### ISSUE THREAD

**Issue by fredrikbaberg** [djade007/latext#1]
Hi,
Thank you for this package! I did a work-around by splitting the content between text and equations but had issues when I needed to split the content into multiple lines, this should clean up the code a lot.

I noticed the text and equation are vertically offset; do you think that is easy to resolve?

Example: ![image](https://user-images.githubusercontent.com/19709460/233323617-72e49f5c-b98e-4023-8bd5-d27449164af1.png)
```
child: LaTexT(
  laTeXCode: Text(
    r"A-$\alpha$-B",
    style: Theme.of(context)
        .textTheme
        .bodyLarge
        ?.copyWith(color: Colors.red),
  ),
),
```

**Comment by djade007** [comment]
I'm not able to replicate.

It looks like this on my end: <img width="87" alt="sns" src="https://github.com/djade007/latext/assets/8323355/4d5cd18c-d402-4881-b70c-c404976089c3">

**Comment by fredrikbaberg** [comment]
I'll check this again, as soon as I've gotten it to run again (updated Flutter, see #3).
