### ISSUE TITLE
Different start and end delimiter

### ISSUE THREAD

**Issue by RichardRaue** [djade007/latext#13]
Hi,

thank you for this lib. I am trying to parse a GPT response with your lib. Unfortunately, GPT returns LaTeX code with a start and end delimiter that are NOT the same. 

So GPT-LateX block 
starts with `'\['` and 
ends with `'\]'`, 

inline LaTeX 
starts with `'\('` and 
ends with` '\)'`.

Is there a way to add different delimiters for start and end of a LaTeX string? Thank you in advance!

Best,
Richard

**Comment by djade007** [comment]
Hello, this is currently not supported. I will recommend either cleaning the Latex code yourself, by using find and replace or adding a prompt for ChatGPT to use the same start and end delimiter.
