### ISSUE TITLE
Latex will show error when it too long

### ISSUE THREAD

**Issue by jackychiu0207** [djade007/latext#2]
When it too long,it will out the width of the device.
Can it auto change line?

**Comment by djade007** [comment]
The overflow error is coming from the [flutter_math](https://github.com/simpleclub-extended/flutter_math_fork) package.

I'll recommend splitting the LaTex equation. Alternatively, you can wrap the equation with a `SingleChildScrollView` widget to enable scrolling and prevent overflow errors.

**Comment by jackychiu0207** [comment]
Thanks a lot.
