### ISSUE TITLE
Display delimiter doesn't work

### ISSUE THREAD

**Issue by prok155** [djade007/latext#6]
I would like to center some part of my latex, for example:

`LaTexT(
              displayDelimiter: r'$$',
              laTeXCode: Text(
                r'Here is the fraction: $$\frac{3}{4}$$',
                style: Theme.of(context).textTheme.bodyMedium,
              ),
            ),`

The fraction 3/4 should be displayed in the center of the screen, currently it is displayed on a new line and it's not centered. Seems like displayDelimiter doesn't work at all.

**Comment by djade007** [comment]
A single `$` works fine.

`LaTexT(laTeXCode: Text( r'Here is the fraction: $\frac{3}{4}$', style: Theme.of(context).textTheme.bodyMedium, ), ),`

**Comment by prok155** [comment]
You can paste `Here is the fraction: $$\frac{3}{4}$$` and `Here is the fraction: $\frac{3}{4}$` to overleaf or any LaTeX editor and you will see what I'm talking about. Look at following screens which will explain this bug:

**Current state:**
![Screenshot_1701190416](https://github.com/djade007/latext/assets/41127794/46ff74de-a1d3-404c-8f24-5c2c2251c1cf)


**Expected result**
![Screenshot_1701189847](https://github.com/djade007/latext/assets/41127794/3e1fec83-43c7-4a37-be2f-fb898e7dab50)


When you use double `$$`, Math expression should be started form a new line and sohuld be centered. With your package it is started from a new line, but it's not centered and it looks ugly.

**Comment by djade007** [comment]
Fixed in version: `0.2.0`
